### PR TITLE
Adding `scheme` to simpl#register defaults

### PR DESCRIPTION
**Pull request by dehidehidehi**
Humble PR after adding `scheme` to my own simpl#register defaults.
Cheers

### CODE REVIEW

**Comment by benknoble** [comment]
Thanks! I'll merge this in with an edited commit message shortly.

**Comment by dehidehidehi** [comment]
As a side note, to execute the `Chez Scheme` REPL using almost only R6RS compliant libraries, the `simpl#register` command is :
```vim
	autocmd FileType scheme call simpl#register('scheme', {
			\ s -> printf("(interaction-environment
			\ (copy-environment
			\ (environment '(rnrs) '(rnrs eval) '(rnrs mutable-pairs)
			\ '(rnrs mutable-strings) '(rnrs r5rs)
			\ '(only (chezscheme) library import debug load)) \#t))\n
			\ (load \"%s\")\n", s)
			\ }, {
			\ -> 'load '
			\ })
```

Source:
Section 2.3. The Interaction Environment
https://scheme.com/csug8/use.html
```text
To be useful for most purposes, library and import should probably also be included, from the (chezscheme) library.

(interaction-environment
  (copy-environment
    (environment
      '(rnrs)
      '(rnrs eval) 
      '(rnrs mutable-pairs) 
      '(rnrs mutable-strings) 
      '(rnrs r5rs)
      '(only (chezscheme) library import))
    #t))
```

**Comment by benknoble** [comment]
I don't know much about running Chez's REPL, but the good news is _that_ bit of configuration should be done with `b:interpreter`. The `simpl#register` for loads should be "interpreter agnostic" (and doesn't need to be in an ftplugin autocommand)

**Comment by benknoble** [comment]
Future readers: if you land here because you have a Scheme file with a `"` in the name and this breaks, try `{ s -> printf("(load \"%s\")\n", escape(s, '"'))}` and let me know how it goes.

**Pull request closed without merging**
